name: PiggyAuth
main: PiggyAuth\Main
version: 2.0.1
api: [2.0.0]
load: POSTWORLD
author: MCPEPIG
permissions:
 piggyauth:
  default: op
  description: "Allows using all PiggyAuth features" 
  children:
    piggyauth.command:
      default: op
      description: "Allow using all PiggyAuth commands"
      children:
        piggyauth.command.login:
          default: true
          description: "Allow using /login"
        piggyauth.command.register:
          default: true
          description: "Allow using /register"
        piggyauth.command.changeemail:
          default: true
          description: "Allow using /changeemail"
        piggyauth.command.changepassword:
          default: true
          description: "Allow using /changepassword"
        piggyauth.command.forgotpassword:
          default: true
          description: "Allow using /forgotpassword"
        piggyauth.command.pin:
          default: true
          description: "Allow using /pin"
        piggyauth.command.resetpassword:
          default: op
          description: "Allow using /resetpassword"
        piggyauth.command.sendpin:
          default: true
          description: "Allow using /sendpin"
        piggyauth.command.logout:
          default: true
          description: "Allow using /logout"
