#                                                                                                      
#,-.----.                                                                                              
#\    /  \                                             ,---,                        ___      ,---,     
#|   :    \   ,--,                                    '  .' \                     ,--.'|_  ,--.' |     
#|   |  .\ :,--.'|                                   /  ;    '.             ,--,  |  | :,' |  |  :     
#.   :  |: ||  |,     ,----._,.  ,----._,.          :  :       \          ,'_ /|  :  : ' : :  :  :     
#|   |   \ :`--'_    /   /  ' / /   /  ' /     .--, :  |   /\   \    .--. |  | :.;__,'  /  :  |  |,--. 
#|   : .   /,' ,'|  |   :     ||   :     |   /_ ./| |  :  ' ;.   : ,'_ /| :  . ||  |   |   |  :  '   | 
#;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' : |  |  ;/  \   \|  ' | |  . .:__,'| :   |  |   /' : 
#|   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: | '  :  | \  \ ,'|  | ' |  | |  '  : |__ '  :  | | | 
#:   ' |    '  : |__'   .   . |'   .   . |.  \  ' | |  |  '  '--'  :  | : ;  ; |  |  | '.'||  |  ' | : 
#:   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   : |  :  :        '  :  `--'   \ ;  :    ;|  :  :_:,' 
#|   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ; |  | ,'        :  ,      .-./ |  ,   / |  | ,'     
#`---'.|    |  ,   / |   :    : |   :    :   :  \  \`--''           `--`----'      ---`-'  `--''       
#  `---`     ---`-'   \   \  /   \   \  /     \  ' ;                                                   
#                      `--`-'     `--`-'       `--`                                                    

#If enabled, movement will be alowed will be allowed when not authenticated
allow-movement: false
#If enabled, you can login without /login
chat-login: true
#If enabled, you will be authenticated automatically if your uuid matches the last uuid used.
auto-authentication: false
#Minimum password length
minimum-password-length: 6
#Seconds before kicked if not authenticated
timeout: 60
#Tries before kicked
tries: 5
#If enabled, a popup will be shown when not authenticated
popup: true
#If enabled, a tip will be shown when not authenticated
tip: true
#Seconds til next message
seconds-til-next-message: 5
#If enabled, players will be invisible til authentication
invisible: true
#If enabled, players will be blind til authentication
blindness: true
#If enabled, players can see chat messages when not authenticted
see-messages: false
#if enabled, players joining when another player has their username is kicked
single-session: true

#Messages
join-message: "§6This server requires an account."
authentication-success: "§aYou have been authenticated."
already-authenticated: "§cYou have already logged in."
incorrect-password: "§cIncorrect password."
register-success: "§cYou have been registered."
already-registered: "§cYou are already registered."
password-too-short: "§cPassword is too short"
confirm-password: "§aPlease confirm your password."
password-not-match: "§cYour password is not the same"
not-registered: "§cYou are not registered."
dont-say-password: "§cDo not say your password."
register: "§6Please register by typing in /register <password>"
login: "§6Please login by typing in /login <password>"
register-popup: "§6Please register."
register-tip: "§6Please register."
login-popup: "§6Please login."
login-tip: "§6Please login."
timeout-message: "§6Login Timeout"